export const data_thongbao = [
    {
        id: 1,
        date: '21/08/2023',
        title: 'THÔNG BÁO VỀ VIỆC TỔ CHỨC HỘI NGHỊ ĐẠI BIỂU VIÊN CHỨC, NGƯỜI LAO ĐỘNG NĂM 2023-2024',
        text: 'Nội dung và văn bản về việc tổ chức hội nghị đại biểu viên chức, người lao động năm 2023-2024 Nội dung và văn bản về việc tổ chức hội nghị đại biểu viên chức, người lao động năm 2023-2024 Nội dung và văn bản về việc tổ chức hội nghị đại.Nội dung và văn bản về việc tổ chức hội nghị đại biểu viên chức, người lao động năm 2023-2024 Nội dung và văn bản về việc tổ chức hội nghị đại biểu viên chức, người lao động năm 2023-2024 Nội dung và văn bản về việc tổ chức hội nghị đại ',
    },
    {
        id: 2,
        date: '21/08/2023',
        title: 'KHÓA LUẬN TỐT NGHIỆP ĐỢT 1 NĂM HỌC 2023-2024',
        text: 'Không phải vết thương nào cũng chảy máu. Và cũng không phải không chảy máu là không bị đau. ',
    },
    {
        id: 3,
        date: '21/08/2023',
        title: 'THỰC TẬP TỐT NGHIỆP ĐỢT 1 NĂM HỌC 2023-2024',
        text: 'Cuộc sống đầy ắp những việc không như ý, chúng ta chẳng thể nào né tránh. Điều duy nhất có thể làm là thay đổi góc nhìn về nó.',
    },
    {
        id: 4,
        date: '21/08/2023',
        title: '4THÔNG BÁO VỀ VIỆC TỔ CHỨC HỘI NGHỊ ĐẠI BIỂU VIÊN CHỨC, NGƯỜI LAO ĐỘNG NĂM 2023-2024',
        text: 'Điểm yếu khi ta còn trẻ là dễ mắc những sai lầm trong cuộc sống. Nhưng bù lại, chúng ta có sức sống mạnh mẽ. Dễ dàng hỏi phục và vươn lên.',
    },
    {
        id: 5,
        date: '21/08/2023',
        title: 'LỄ HỘI NĂM HỌC 2023-2024',
        text: 'Thời gian là thứ quý giá mà cuộc sống ban tặng. Nó có thể đưa mọi thứ vào trong lãng quên.',
    },
    {
        id: 6,
        date: '21/08/2023',
        title: '6THÔNG BÁO VỀ VIỆC TỔ CHỨC HỘI NGHỊ ĐẠI BIỂU VIÊN CHỨC, NGƯỜI LAO ĐỘNG NĂM 2023-2024',
        text: '.Ánh sáng đi trước âm thanh, vì thế, con người ta trông có vẻ thông minh cho đến khi ta nghe họ phát biểu. ',
    }
]


export const data_CNCNTT = [
    {
        masv: '3119560010',
        ho: 'Lê Thị Cẩm',
        ten: 'Duyên',
        diem: 2.97,
        chuyennganh: 'Hệ thống thông tin',
        trangthai: 1,
    },
    {
        masv: '3119560011',
        ho: 'Lê Thị Cẩm',
        ten: 'Duyên',
        diem: 2.97,
        chuyennganh: 'Chưa đăng ký',
        trangthai: 1,
    },
    {
        masv: '3119560012',
        ho: 'Lê Thị Cẩm',
        ten: 'Duyên',
        diem: 2.97,
        chuyennganh: 'Chưa đăng ký',
        trangthai: 1,
    },
    {
        masv: '3119560013',
        ho: 'Lê Thị Cẩm',
        ten: 'Duyên',
        diem: 2.97,
        chuyennganh: 'Chưa đăng ký',
        trangthai: 1,
    },
    {
        masv: '3119560014',
        ho: 'Lê Thị Cẩm',
        ten: 'Duyên',
        diem: 2.97,
        chuyennganh: 'Kỹ thuật phần mềm',
        trangthai: 1,
    },
]
export const data_CNKTPM = [
    {
        masv: '3119560010',
        ho: 'Lê Thị Cẩm',
        ten: 'Duyên',
        diem: 2.97,
        chuyennganh: 'Chưa đăng ký',
        trangthai: 1,
    },
    {
        masv: '3119560011',
        ho: 'Lê Thị Cẩm',
        ten: 'Duyên',
        diem: 2.97,
        chuyennganh: 'Lập trình web',
        trangthai: 1,
    },
    {
        masv: '3119560012',
        ho: 'Lê Thị Cẩm',
        ten: 'Duyên',
        diem: 2.97,
        chuyennganh: 'Lập trình ứng dụng',
        trangthai: 1,
    },
    {
        masv: '3119560010',
        ho: 'Lê Thị Cẩm',
        ten: 'Duyên',
        diem: 2.97,
        chuyennganh: 'Chưa đăng ký',
        trangthai: 1,
    },
    {
        masv: '3119560010',
        ho: 'Lê Thị Cẩm',
        ten: 'Duyên',
        diem: 2.97,
        chuyennganh: 'Chưa đăng ký',
        trangthai: 1,
    },
    {
        masv: '3119560010',
        ho: 'Lê Thị Cẩm',
        ten: 'Duyên',
        diem: 2.97,
        chuyennganh: 'Chưa đăng ký',
        trangthai: 1,
    },
]


export const data_khoaluan = [
    {
        ten: 'Phần mềm quản lý ghi chú cá nhân với tính năng nhận dạng tiếng nói',
        giangvienhuongdan: 'Nguyễn Tuấn Đăng',
        donvi: 'Khoa CNTT',
        sinhvien1: 'Lê Thị Cẩm Duyên',
        MSSV1: '3119560010',
        TC1: '152',
        TB1: '2.99',
        Email1: 'tupinkyy@gmail.com',
        Sdt1: '386260727',
        sinhvien2: 'Lê Thị Cẩm Duyên 2',
        MSSV2: '3119560018',
        TC2: '156',
        TB2: '3.3',
        Email2: 'hoanghavy0207@gmail',
        Sdt2: '386260727',
        trangthai: 1,
    },
    {
        ten: 'Phần mềm quản lý ghi chú cá nhân với tính năng nhận dạng tiếng nói',
        giangvienhuongdan: 'Nguyễn Tuấn Đăng',
        donvi: 'Khoa CNTT',
        sinhvien1: '',
        MSSV1: '',
        TC1: '',
        TB1: '',
        Email1: '',
        Sdt1: '',
        sinhvien2: '',
        MSSV2: '',
        TC2: '',
        TB2: '',
        Email2: '',
        Sdt2: '',
        trangthai: 1,
    },
    {
        ten: 'Phần mềm quản lý ghi chú cá nhân với tính năng nhận dạng tiếng nói',
        giangvienhuongdan: 'Nguyễn Tuấn Đăng',
        donvi: 'Khoa CNTT',
        sinhvien1: 'Lê Thị Cẩm Duyên',
        MSSV1: '3119560010',
        TC1: '152',
        TB1: '2.99',
        Email1: 'tupinkyy@gmail.com',
        Sdt1: '386260727',
        sinhvien2: 'Lê Thị Cẩm Duyên 2',
        MSSV2: '3119560018',
        TC2: '156',
        TB2: '3.3',
        Email2: 'hoanghavy0207@gmail',
        Sdt2: '386260727',
        trangthai: 1,
    },
    {
        ten: 'Phần mềm quản lý ghi chú cá nhân với tính năng nhận dạng tiếng nói',
        giangvienhuongdan: 'Nguyễn Tuấn Đăng',
        donvi: 'Khoa CNTT',
        sinhvien1: 'Lê Thị Cẩm Duyên',
        MSSV1: '3119560010',
        TC1: '152',
        TB1: '2.99',
        Email1: 'tupinkyy@gmail.com',
        Sdt1: '386260727',
        sinhvien2: '',
        MSSV2: '',
        TC2: '',
        TB2: '',
        Email2: '',
        Sdt2: '',
        trangthai: 1,
    },
    {
        ten: 'Phần mềm quản lý ghi chú cá nhân với tính năng nhận dạng tiếng nói',
        giangvienhuongdan: 'Nguyễn Tuấn Đăng',
        donvi: 'Khoa CNTT',
        sinhvien1: '',
        MSSV1: '',
        TC1: '',
        TB1: '',
        Email1: '',
        Sdt1: '',
        sinhvien2: '',
        MSSV2: '',
        TC2: '',
        TB2: '',
        Email2: '',
        Sdt2: '',
        trangthai: 1,
    },
    {
        ten: 'Xây dựng website đánh giá nhân viên hàng năm',
        giangvienhuongdan: 'Phạm Thi Vương',
        donvi: 'Viện KHDL - TTNT',
        sinhvien1: 'Lê Thị Cẩm Duyên',
        MSSV1: '3119560010',
        TC1: '152',
        TB1: '2.99',
        Email1: 'tupinkyy@gmail.com',
        Sdt1: '386260727',
        sinhvien2: 'Lê Thị Cẩm Duyên 2',
        MSSV2: '3119560018',
        TC2: '156',
        TB2: '3.3',
        Email2: 'hoanghavy0207@gmail',
        Sdt2: '386260727',
        trangthai: 1,
    },
];